name: Test Dockerfile

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm/v6
          # - linux/arm/v7
          - linux/arm64
        php:
          - 8.0
          - 8.1
          - 8.2
        variant:
          - "" # cli
          - fpm
        os:
          - ""
          - alpine

    steps:
      - name: testing matrix values
        run: echo "${{ matrix}} - ${{ matrix.php }} - ${{ matrix.variant }} - ${{ matrix.os }} "
