name: Test Dockerfile

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          # - 8.0
          - 8.1
          # - 8.2
        os:
          # - ""
          - alpine
        variant:
          - "" # cli
          # - fpm

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          context: "{{defaultContext}}:{{ matrix.php }}/{{ matrix.os }}"
          platforms: linux/amd64,linux/arm64
          tags: fizzka/docker-phalcon:${{ matrix.php }}-${{ matrix.os }}
